version: "3.9"
services:
  microservices:
    image: "aspdotnetapp"
    container_name: api_app
    build:
      context: .
    ports:
      - "3000:3000"
    networks:
      - apiapp-network
    depends_on:
      - sql
  sql:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: sql_server2019
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=/1A2b3c4d
    networks:
      - apiapp-network
networks:
  apiapp-network:
    driver: bridge